---

- name: Get start timestamp
  hosts: deploy
  connection: local
  tasks:
    - set_fact:
        starttime: "{{ ansible_date_time }}"

- name: Install OpenVPN
  hosts: deploy
  connection: local
  roles:
    - install_openvpn

- name: Generating Keys and Certificates
  hosts: deploy
  connection: local
  roles:
    - gen_keys_certs

- name: Inform the installer
  hosts: deploy
  connection: local
  tasks:
    - debug:
        msg: >-
          The deploy started at {{ hostvars.deploy.starttime.time }},
          ended at {{ ansible_date_time.time }}
