---

- name: Install epel
  yum:
    name: epel-release
    state: latest

- name: Install openvpn and wget
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - openvpn
    - wget

- name: Download easy-rsa for gen ca/keys/certs
  get_url:
    url: https://github.com/OpenVPN/easy-rsa-old/archive/2.3.3.tar.gz
    dest: /tmp/easyrsa

- name: Untar easyrsa
  unarchive:
    src: /tmp/easyrsa
    dest: /tmp

- name: Create easy-rsa directory
  file:
    name: /etc/openvpn/easy-rsa
    state: directory

- name: Copy rsa files to easy-rsa
  copy:
    src: /tmp/easy-rsa-old-2.3.3/easy-rsa/2.0/{{ item }}
    dest: /etc/openvpn/easy-rsa
    owner: root
    group: root
    mode: preserve
  with_items:
    - build-ca
    - build-dh
    - build-inter
    - build-key
    - build-key-pass
    - build-key-pkcs12
    - build-key-server
    - build-req
    - build-req-pass
    - clean-all
    - inherit-inter
    - list-crl
    - openssl-1.0.0.cnf
    - pkitool
    - revoke-full
    - sign-req
    - vars
    - whichopensslcnf


- name: Generate server.conf
  template:
    src: server.conf.j2
    dest: /etc/openvpn/server.conf
