---

- name: Create keys directory
  file:
    name: /etc/openvpn/easy-rsa/keys
    state: directory

- name: Generate vars variables file
  template:
    src: vars.j2
    dest: /etc/openvpn/easy-rsa/vars

- name: Copy bootstrap script
  copy:
    src: files/{{ item }}
    dest: /opt
    mode: preserve
  with_items:
    - gen_server_keys_certs.sh
    - vpn_env.sh

- name: Generate server keys and certs
  script: /opt/gen_server_keys_certs.sh

- name: Routing
  script: /opt/vpn_env.sh

- name: Start openvpn service
  service:
    name: openvpn@server
    enabled: yes
    state: started

